version: '3.9'

services:
  app:
    build: .
    ports: 
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: ${PG_USER}
        POSTGRES_PASSWORD: ${PG_PASSWORD}
        POSTGRES_DB: ${PG_DB}
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
